services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_worker
    command: celery -A celery_app.celery worker --pool=threads --concurrency=20 --loglevel=info 
    environment:
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  

