services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    restart: always
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_worker
    command: celery -A celery_app.celery worker --pool=threads --concurrency=20 --loglevel=info 
    environment:
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: local_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru   


volumes:
  redis_data:

